apply plugin: 'com.android.application'

android {
    namespace 'com.avtoonline.pdd'
    compileSdk 34

    defaultConfig {
        applicationId "com.avtoonline.pdd"
        minSdk 24
        targetSdk 34
        versionCode 1
        versionName "1.0.0"
    }

    signingConfigs {
        release {
            storeFile file('my-release-key.jks')
            storePassword 'password123'
            keyAlias 'my-alias'
            keyPassword 'password123'
        }
    }

    buildTypes {
        release {
            minifyEnabled false
            signingConfig signingConfigs.release
        }
        debug {
            signingConfig signingConfigs.release
        }
    }

    compileOptions {
        sourceCompatibility JavaVersion.VERSION_1_8
        targetCompatibility JavaVersion.VERSION_1_8
    }
}

dependencies {
    implementation 'androidx.appcompat:appcompat:1.6.1'
}

try {
    def servicesJSON = file('google-services.json')
    if (servicesJSON.exists()) {
        apply plugin: 'com.google.gms.google-services'
    }
} catch(Exception e) {
    logger.info("google-services.json not found")
}

try {
    apply from: 'capacitor.build.gradle'
} catch (Exception e) {
    logger.info("capacitor.build.gradle not found")
}
